#pragma once

// Screen Size
#define SCREEN_SIZE_X 160
#define SCREEN_SIZE_Y 50

//// Key Code
//#define KEYCODE_LEFT 0x25
//#define KEYCODE_UP 0x26
//#define KEYCODE_RIGHT 0x27
//#define KEYCODE_DOWN 0x28
//#define KEYCODE_SPACE 0x20
//#define KEYCODE_ESCAPE 0x1B

// Char
#define CHAR_BASE ' '

// Color
#define COLOR_BASE	0x00		// 기본 색깔 - 배경(검정), 폰트(검정)

#define COLOR_FONT_BLACK 0x00
#define COLOR_FONT_BLUE 0x01
#define COLOR_FONT_GREEN 0x02
#define COLOR_FONT_AQUA 0x03
#define COLOR_FONT_RED 0x04
#define COLOR_FONT_PURPLE 0x05
#define COLOR_FONT_YELLOW 0x06
#define COLOR_FONT_WHITE 0x07
#define COLOR_FONT_GRAY 0x08
#define COLOR_FONT_LIGHTBLUE 0x09
#define COLOR_FONT_LIGHTGREEN 0x0A
#define COLOR_FONT_LIGHTAQUA 0x0B
#define COLOR_FONT_LIGHTRED 0x0C
#define COLOR_FONT_LIGHTPURPLE 0x0D
#define COLOR_FONT_LIGHTYELLOW 0x0E
#define COLOR_FONT_LIGHTWHITE 0x0F

#define COLOR_BG_BLACK 0x00
#define COLOR_BG_BLUE 0x10
#define COLOR_BG_GREEN 0x20
#define COLOR_BG_AQUA 0x30
#define COLOR_BG_RED 0x40
#define COLOR_BG_PURPLE 0x50
#define COLOR_BG_YELLOW 0x60
#define COLOR_BG_WHITE 0x70
#define COLOR_BG_GRAY 0x80
#define COLOR_BG_LIGHTBLUE 0x90
#define COLOR_BG_LIGHTGREEN 0xA0
#define COLOR_BG_LIGHTAQUA 0xB0
#define COLOR_BG_LIGHTRED 0xC0
#define COLOR_BG_LIGHTPURPLE 0xD0
#define COLOR_BG_LIGHTYELLOW 0xE0
#define COLOR_BG_LIGHTWHITE 0xF0


// Layer
#define LAYER_BASE 0
// menu
#define LAYER_TITLE 10
// game
#define LAYER_BACKGROUND 100
#define LAYER_GAMEOBJECT 200
#define LAYER_PLAYER 300
#define LAYER_COSTUME 400
#define LAYER_MESSAGEBOX 500
#define LAYER_MESSAGEBOX_SELECT 200

// setting
#define LAYER_SETTINGMENU 200
#define LAYER_SETTINGLIST 205
#define LAYER_SETTINGLIST_SELECT 210
#define LAYER_SETTING_UPGRADE_MESSAGEBOX 250
#define LAYER_SETTING_MESSAGEBOX 250

// Control Message
// Manager의 update함수에서 리턴해주는 값
#define CONTROL_MESSAGE_QUIT 0
#define CONTROL_MESSAGE_CONTINUE 1
#define CONTROL_MESSAGE_START_GAME 2
#define CONTROL_MESSAGE_START_MENU 3
#define CONTROL_MESSAGE_START_SETTING 4
#define CONTROL_MESSAGE_START_RESULT 5
#define CONTROL_MESSAGE_START_HOWTO 6
#define CONTROL_MESSAGE_START_CREATOR 7

// game state
#define STATE_QUIT -1
#define STATE_MENU 0
#define STATE_GAME 1
#define STATE_SETTING 2
#define STATE_RESULT 3
#define STATE_HOWTO 4
#define STATE_CREATOR 5

// image number
#define PIXELOBJ_TITLE 1
#define PIXELOBJ_GROUND 2
#define PIXELOBJ_CEILING 3
#define PIXELOBJ_BACKGROUND 4
#define PIXELOBJ_GAMEOVER 5
#define PIXELOBJ_HOWTO 6

#define PIXELOBJ_COSTUME_SHIELD_EMPTY 8
#define PIXELOBJ_COSTUME_HAT_BLACKCAP 9
#define PIXELOBJ_COSTUME_HAT_BASE 0x1000
#define PIXELOBJ_COSTUME_HAT_RED 0x1000
#define PIXELOBJ_COSTUME_HAT_AQUA 0x1001
#define PIXELOBJ_COSTUME_HAT_PURPLE 0x1002
#define PIXELOBJ_COSTUME_HAT_BLUE 0x1003
#define PIXELOBJ_COSTUME_HAT_EMPTY 0x100F

#define PIXELOBJ_COSTUME_CLOAK_BASE 0x2000
#define PIXELOBJ_COSTUME_CLOAK_RED 0x2004
#define PIXELOBJ_COSTUME_CLOAK_AQUA 0x2005
#define PIXELOBJ_COSTUME_CLOAK_PURPLE 0x2006
#define PIXELOBJ_COSTUME_CLOAK_BLUE 0x2007
#define PIXELOBJ_COSTUME_CLOAK_EMPTY 0x200F

#define OBSTACLE_TYPE_BOTTOM 0
#define OBSTACLE_TYPE_TOP 1
#define OBSTACLE_TYPE_DASH_BOTTOM 2

#define ITEM_TYPE_POINTBOX 0
#define ITEM_TYPE_POWERBOX 1
#define ITEM_TYPE_SHIELD 2

// item
#define ITEM_POWERBOX_APPEARANCE_PROBABILITY 50
#define ITEM_SHIELD_APPEARANCE_PROBABILITY 2

// image size, location
#define PLAYER_SIZE_X 4
#define PLAYER_SIZE_Y 5
#define PLAYER_SLIDING_SIZE_Y 2

#define CEILING_LOCATION_Y 0
#define CEILING_SIZE_X 160
#define CEILING_SIZE_Y 15

#define GROUND_LOCATION_Y 35
#define GROUND_SIZE_X 160
#define GROUND_SIZE_Y 15

#define OBSTACLE_BSIZE_X 10
#define OBSTACLE_BSIZE_Y 8
#define OBSTACLE_TSIZE_X 30
#define OBSTACLE_TSIZE_Y 17
#define OBSTACLE_DBSIZE_X 20
#define OBSTACLE_DBSIZE_Y 5

#define POWERBAR_LOCATION_X 6
#define POWERBAR_LOCATION_Y 37
#define POWERBAR_TEXT_SIZE_X 6
#define POWERBAR_SIZE_X 20
#define POWERBAR_SIZE_Y 1

// image color
#define POINTBOX_COLOR 0x60
#define POWERBOX_COLOR 0x40
#define SHIELD_COLOR 0x10

#define COSTUME_HAT_SIZEX 6
#define COSTUME_HAT_SIZEY 3
#define COSTUME_CLOAK_SIZEX 10
#define COSTUME_CLOAK_SIZEY 2
#define COSTUME_SHIELD_SIZEX 4
#define COSTUME_SHIELD_SIZEY 5

// section
#define SECTION_BBT 0
#define SECTION_BTB 1
#define SECTION_TBB 2
#define SECTION_TTB 3
#define SECTION_TBT 4
#define SECTION_BTT 5

#define SECTION_BASE_SIZE 6

#define SECTION_HARDSECTION_DBBT 6
#define SECTION_HARDSECTION_TBDB 7


#define SECTION_SAFE_SPACE 20
#define SECTION_HARD_SAFE_SPACE 10

// message object
#define ALIGNMENT_CENTER 0
#define ALIGNMENT_LEFT 1
#define ALIGNMENT_RIGHT 2

// power
#define POWER_DASH 200

// save
#define SAVE_KEY_MAXSCORE 0
#define SAVE_KEY_DOT 1
#define SAVE_KEY_COSTUME 2
#define SAVE_KEY_UPGRADE_POINT 3
#define SAVE_KEY_UPGRADE_POWER 4
#define SAVE_KEY_UPGRADE_PROBABILITY 5
#define SAVE_KEY_COSTUME0 6
#define SAVE_KEY_COSTUME1 7
#define SAVE_KEY_COSTUME2 8
#define SAVE_KEY_COSTUME3 9
#define SAVE_KEY_COSTUME4 10
#define SAVE_KEY_COSTUME5 11
#define SAVE_KEY_COSTUME6 12
#define SAVE_KEY_COSTUME7 13

#define DEFAULT_DATA_MAXSCORE 0
#define DEFAULT_DATA_DOT 0
#define DEFAULT_DATA_COSTUME 0xff
#define DEFAULT_DATA_UPGRADE_POINT 0
#define DEFAULT_DATA_UPGRADE_POWER 0
#define DEFAULT_DATA_UPGRADE_PROBABILITY 0
#define DEFAULT_DATA_COSTUME0 0
#define DEFAULT_DATA_COSTUME1 0
#define DEFAULT_DATA_COSTUME2 0
#define DEFAULT_DATA_COSTUME3 0
#define DEFAULT_DATA_COSTUME4 0
#define DEFAULT_DATA_COSTUME5 0
#define DEFAULT_DATA_COSTUME6 0
#define DEFAULT_DATA_COSTUME7 0